// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHI3cJ4bDTAkyzAie3N_GtOoqLdrPTec0',
    appId: '1:379932071210:web:a2777c94db654fad1fba53',
    messagingSenderId: '379932071210',
    projectId: 'flutter-chat-app-433ec',
    authDomain: 'flutter-chat-app-433ec.firebaseapp.com',
    storageBucket: 'flutter-chat-app-433ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjHcLGa01zfGHWQVV1qeEZEYLk9af-Oqg',
    appId: '1:379932071210:android:b1d4da4608a94de21fba53',
    messagingSenderId: '379932071210',
    projectId: 'flutter-chat-app-433ec',
    storageBucket: 'flutter-chat-app-433ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-3IfhvjFyyMkObF-_gc3H7QwDq0NLsBg',
    appId: '1:379932071210:ios:996b1d7be38554771fba53',
    messagingSenderId: '379932071210',
    projectId: 'flutter-chat-app-433ec',
    storageBucket: 'flutter-chat-app-433ec.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-3IfhvjFyyMkObF-_gc3H7QwDq0NLsBg',
    appId: '1:379932071210:ios:996b1d7be38554771fba53',
    messagingSenderId: '379932071210',
    projectId: 'flutter-chat-app-433ec',
    storageBucket: 'flutter-chat-app-433ec.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHI3cJ4bDTAkyzAie3N_GtOoqLdrPTec0',
    appId: '1:379932071210:web:2eeb79e659e67a961fba53',
    messagingSenderId: '379932071210',
    projectId: 'flutter-chat-app-433ec',
    authDomain: 'flutter-chat-app-433ec.firebaseapp.com',
    storageBucket: 'flutter-chat-app-433ec.appspot.com',
  );
}
